<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="study.aspx.cs"
    Inherits="StudyTracker_WF.Study.study" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">


    <%--<div class="jumbotron">
        <asp:Button runat="server" ID="btnClick" OnClick="btnClick_OnClick" CssClass="btn-info btn-lg" Text="Click here to view Studies" ClientIDMode="Static" />
    </div>--%>
<%--    <asp:Button ID="Button1" runat="server" OnClick="btnNew_Click" Text="New Study" />--%>

    <div class="table-responsive">
       <asp:DetailsView ID="DetailsView1" runat="server" CssClass="table table-striped table-bordered"
          AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
          DataSourceID="ObjectDataSource2" AutoGenerateRows="False" OnItemUpdated="DetailsView1_ItemUpdated" DataKeyNames="Id" OnItemDeleted="DetailsView1_ItemDeleted">
           <Fields>
               <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" />
               <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
               <asp:BoundField DataField="PrincipalInvestigator" HeaderText="PrincipalInvestigator" SortExpression="PrincipalInvestigator" />
               <asp:CheckBoxField DataField="Availability" HeaderText="Availability" SortExpression="Availability" />
               <asp:BoundField DataField="CreatedBy" HeaderText="CreatedBy" SortExpression="CreatedBy" />
               <asp:BoundField DataField="CreatedDate" HeaderText="CreatedDate" SortExpression="CreatedDate" />
               <asp:BoundField DataField="UpdatedBy" HeaderText="UpdatedBy" SortExpression="UpdatedBy" />
               <asp:BoundField DataField="UpdatedDate" HeaderText="UpdatedDate" SortExpression="UpdatedDate" />
           </Fields>
       </asp:DetailsView>
    </div>

    <div class="table-responsive">

        <asp:GridView ID="GridView1" runat="server" DataSourceID="ObjectDataSource1" CssClass="table table-striped table-bordered"
            DataKeyNames="Id" AutoGenerateColumns="False">
            <Columns>
               <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" />
               <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
               <asp:BoundField DataField="PrincipalInvestigator" HeaderText="PrincipalInvestigator" SortExpression="PrincipalInvestigator" />
               <asp:CheckBoxField DataField="Availability" HeaderText="Availability" SortExpression="Availability" />
               <asp:CommandField ShowSelectButton="True" />
            </Columns>
        </asp:GridView>

        <asp:ObjectDataSource ID="ObjectDataSource2" runat="server" SelectMethod="GetStudy"
            TypeName="StudyTracker_WF.StudyClasses.StudyManager" DataObjectTypeName="StudyTracker_WF.StudyClasses.Study"
             UpdateMethod="UpdateStudy" DeleteMethod="DeleteStudy">
          
            <SelectParameters>
                <asp:ControlParameter ControlID="GridView1" Name="Id" PropertyName="SelectedValue" Type="Int32" />
            </SelectParameters>
        </asp:ObjectDataSource>
        <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" SelectMethod="GetStudies"
            TypeName="StudyTracker_WF.StudyClasses.StudyManager"></asp:ObjectDataSource>

    </div>


    <div class="form-horizontal">
    <div class="form-group">
        <asp:Label runat="server" for="txtTitle" class="col-sm-2 control-label">Title</asp:Label>
        <div class="col-sm-12">
            <asp:TextBox  class="form-control" ID="txtTitle" placeholder="Title" runat="server" />
        </div>
    </div>

    <div class="form-group">
        <asp:Label runat="server" for="txtPI" class="col-sm-2 control-label">Principal Investigator</asp:Label>
        <div class="col-sm-12">
            <asp:TextBox class="form-control" ID="txtPI" placeholder="Principal Investigator" runat="server" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-12">
            <div class="checkbox">
                <asp:Label runat="server" for="txtavail">
                        <asp:CheckBox ID="txtavail" runat="server"/> Availability
                </asp:Label></div></div></div><div class="form-group">
        <div class="col-sm-offset-2 col-sm-12">
            <asp:button type="submit" class="btn btn-success" OnClick="CreateStudy" runat="server" Text="New Study" ></asp:button>
            <asp:Label runat="server" ID="lblInsertInfo"></asp:Label>
        </div></div></div></asp:Content><asp:Content ID="Content2" ContentPlaceHolderID="EndOfPageContent" runat="server">
  <script>
    // Make DetailView 'Edit', 'Delete', 'New' links show as buttons
    $(document).ready(function () {
      $("td[colspan='2'] a").addClass('btn btn-primary');
    });
  </script>
</asp:Content>

